# Generated by Django 3.0.5 on 2020-05-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofileactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileActivity',
        ),
    ]
